package antplutomigrator.correctness.comparison;

import java.io.File;

/**
 * Created by manuel on 22.06.17.
 */
public class JavaDocDateIgnoredLineComparer implements LineComparer {
    @Override
    public boolean linesAreEqual(File f1, File f2, String l1, String l2) throws Exception {
        if (!f1.getName().endsWith(".html") || !f2.getName().endsWith(".html"))
            return false;

        if (l1.contains("<!-- Generated by javadoc"))
            return true;

        return false;
    }
}
